### ISSUE TITLE
See exact matches that was bet created on

### ISSUE THREAD

**Issue by monkynhko** [iNviNho/hazarder#68]
![image](https://user-images.githubusercontent.com/42342888/44028780-50a3627a-9efb-11e8-89e2-141a46aa11d1.png)
On a click on a game type, there would be useful to see exact results of matches of direct type that was bet, it can be done by a few ways, Either to create a new table. Or just transfer to filetered MyTickets by that type

**Comment by iNviNho** [comment]
Marcingale detailed dashboard will do the trick
