### ISSUE TITLE
Fix Marcingale creating 2 bets on the same match

### ISSUE THREAD

**Issue by monkynhko** [iNviNho/hazarder#74]
![image](https://user-images.githubusercontent.com/42342888/44142529-b5509496-a080-11e8-9534-c9fa9cd94488.png)

Marcingale is creating 2 bets on the same match

**Comment by iNviNho** [comment]
Fuck. I will debug today. Basically we should have per match only one game type bet. So we csnnot bet marcingale 2 times on the same match. 

Add if condition if for this match we already have a ticket. If yes then checknif we already did bet on match option (1,0,2,10,02) we are trying to bet on. If yes = dont create ticket

Thanks, should be ez.

**Comment by iNviNho** [comment]
https://github.com/iNviNho/hazarder/commit/dfb490753cb9ab84e595438209eff5d99580cc39
